In [9]:
df = df_meta.drop(columns=["main_category", "average_rating", "images", "videos", "bought_together"]).copy()

# 3. 保存为新的 JSON 文件（按行写出，每行一个 JSON 对象）
df.to_json("../amazonreview_query\origin_dataset\light_meta_edited.json", orient="records", lines=True, force_ascii=False)
df

,title,subtitle,author,rating_number,features,description,price,store,categories,details,parent_asin
0,Chaucer,"Hardcover – Import, January 1, 2004",{'avatar': 'https://m.media-amazon.com/images/...,29,[],[],8.23,Peter Ackroyd (Author),"[Books, Literature & Fiction, History & Critic...",{'Publisher': 'Chatto & Windus; First Edition ...,0701169850
1,Notes from a Kidwatcher,First Edition,{'avatar': 'https://m.media-amazon.com/images/...,1,[Contains 23 selected articles by this influen...,"[About the Author, SANDRA WILDE, Ph.D., is wid...",3.52,Sandra Wilde (Editor),"[Books, Reference, Words, Language & Grammar]",{'Publisher': 'Heinemann; First Edition (May 2...,0435088688
2,Service: A Navy SEAL at War,"Hardcover – May 8, 2012",{'avatar': 'https://m.media-amazon.com/images/...,3421,"[Marcus Luttrell, author of the #1 bestseller,...","[Review, Praise for SERVICE""An action-packed.....",17.17,"Marcus Luttrell (Author), James D. Hornfischer","[Books, Biographies & Memoirs, Leaders & Notab...","{'Publisher': 'Little, Brown and Company; 1st ...",0316185361
3,Monstrous Stories #4: The Day the Mice Stood S...,"Paperback – October 29, 2013",None,40,"[Funny, light-hearted monster stories that are...",[],7.43,Dr. Roach (Author),"[Books, Children's Books, Science Fiction & Fa...",{'Publisher': 'Scholastic Paperbacks; Reprint ...,0545425573
4,Parker & Knight,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...,381,"[From REMINGTON KANE, the author of The Taken!...",[],0.00,Remington Kane (Author) Format: Kindle Edition,"[Books, Mystery, Thriller & Suspense, Thriller...","{'Publication date': 'May 18, 2014', 'Language...",B00KFOP3RG
...,...,...,...,...,...,...,...,...,...,...,...
195,The Secret Thoughts of an Unlikely Convert : A...,"Paperback – January 1, 2012",{'avatar': 'https://m.media-amazon.com/images/...,2645,"[Rosaria, by the standards of many, was living...",[],14.00,Rosaria Champagne Butterfield (Author),"[Books, Biographies & Memoirs, Leaders & Notab...",{'Publisher': 'Crown & Covenant; 1st edition (...,1884527388
196,THE ESSENTIAL GUIDE TO WRITING WELL AND GETTIN...,"Paperback – August 9, 2017",{'avatar': 'https://m.media-amazon.com/images/...,3,"[Over the course of many years, college studen...","[About the Author, Robert Banfelder is an awar...",29.99,Robert Banfelder (Author),"[Books, Education & Teaching]",{'Publisher': 'Broadwater Books; 1st edition (...,0991591291
197,SCUBA SHARK - Diving - Vinyl Car Decal Sticker...,None,None,16,[],[],NaN,None,"[Books, Sports & Outdoors, Water Sports]","{'Item Weight': '3.04 ounces', 'Dimensions': '...",B001INQIPE
198,la_guerra_secreta,"Paperback – January 1, 2004",{'avatar': 'https://m.media-amazon.com/images/...,6,"[1963,El complot,da culminacion a la trilogia,...",[],NaN,Spanish Edition fabia...,"[Books, Libros en español]",{'Publisher': 'editorial de ciencia sociales.;...,9590606148
199,Coleman National Forest Campground and Recreat...,"Paperback – December 1, 2000",None,22,"[There are over 4,300 National Forest campgrou...","[From the Back Cover, There are over 4,300 Nat...",45.97,Our Forests Inc. (Author),"[Books, Sports & Outdoors, Hiking & Camping]",{'Publisher': 'UNKNO; First Edition (December ...,0762707879

In [31]:
import pandas as pd

# 读取 JSON 文件
df_meta = pd.read_json("../amazonreview_query\origin_dataset/books_info.json", lines=True)
df_review = pd.read_json("../amazonreview_query\origin_dataset/review_query.json", lines=True, convert_dates=False)

In [15]:
df_meta

,title,subtitle,author,rating_number,features,description,price,store,categories,details,parent_asin
0,Chaucer,"Hardcover – Import, January 1, 2004",{'avatar': 'https://m.media-amazon.com/images/...,29,[],[],8.23,Peter Ackroyd (Author),"[Books, Literature & Fiction, History & Critic...","Published by Chatto & Windus, the first editio...",0701169850
1,Notes from a Kidwatcher,First Edition,{'avatar': 'https://m.media-amazon.com/images/...,1,[Contains 23 selected articles by this influen...,"[About the Author, SANDRA WILDE, Ph.D., is wid...",3.52,Sandra Wilde (Editor),"[Books, Reference, Words, Language & Grammar]","This book, published by Heinemann in its first...",0435088688
2,Service: A Navy SEAL at War,"Hardcover – May 8, 2012",{'avatar': 'https://m.media-amazon.com/images/...,3421,"[Marcus Luttrell, author of the #1 bestseller,...","[Review, Praise for SERVICE""An action-packed.....",17.17,"Marcus Luttrell (Author), James D. Hornfischer","[Books, Biographies & Memoirs, Leaders & Notab...","This book, published by Little, Brown and Comp...",0316185361
3,Monstrous Stories #4: The Day the Mice Stood S...,"Paperback – October 29, 2013",None,40,"[Funny, light-hearted monster stories that are...",[],7.43,Dr. Roach (Author),"[Books, Children's Books, Science Fiction & Fa...","This book, published by Scholastic Paperbacks ...",0545425573
4,Parker & Knight,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...,381,"[From REMINGTON KANE, the author of The Taken!...",[],0.00,Remington Kane (Author) Format: Kindle Edition,"[Books, Mystery, Thriller & Suspense, Thriller...","The book was published on May 18, 2014, and is...",B00KFOP3RG
...,...,...,...,...,...,...,...,...,...,...,...
195,The Secret Thoughts of an Unlikely Convert : A...,"Paperback – January 1, 2012",{'avatar': 'https://m.media-amazon.com/images/...,2645,"[Rosaria, by the standards of many, was living...",[],14.00,Rosaria Champagne Butterfield (Author),"[Books, Biographies & Memoirs, Leaders & Notab...","This book, published by Crown & Covenant in it...",1884527388
196,THE ESSENTIAL GUIDE TO WRITING WELL AND GETTIN...,"Paperback – August 9, 2017",{'avatar': 'https://m.media-amazon.com/images/...,3,"[Over the course of many years, college studen...","[About the Author, Robert Banfelder is an awar...",29.99,Robert Banfelder (Author),"[Books, Education & Teaching]","The book, published by Broadwater Books in its...",0991591291
197,SCUBA SHARK - Diving - Vinyl Car Decal Sticker...,None,None,16,[],[],NaN,None,"[Books, Sports & Outdoors, Water Sports]",The book has a weight of 3.04 ounces and its d...,B001INQIPE
198,la_guerra_secreta,"Paperback – January 1, 2004",{'avatar': 'https://m.media-amazon.com/images/...,6,"[1963,El complot,da culminacion a la trilogia,...",[],NaN,Spanish Edition fabia...,"[Books, Libros en español]","The book, published by Editorial de Ciencia So...",9590606148
199,Coleman National Forest Campground and Recreat...,"Paperback – December 1, 2000",None,22,"[There are over 4,300 National Forest campgrou...","[From the Back Cover, There are over 4,300 Nat...",45.97,Our Forests Inc. (Author),"[Books, Sports & Outdoors, Hiking & Camping]","This book, published in its first edition on D...",0762707879

In [32]:
df_review

,rating,title,text,parent_asin,review_time,helpful_vote,verified_purchase
0,4,Ha! On me! I thought this was a cookbook!,Lucky for me it's more than a cookbook.<br /><...,0385529813,"November 24, 2012 at 06:52 PM",0,False
1,4,Four Stars,Not as developed as Stephanie but I like the c...,1250074274,"December 31, 2015 at 01:35 PM",0,True
2,4,A wonderful adventure in France,I loved this book all the way until the end. I...,1457514575,"May 05, 2013 at 10:47 AM",1,False
3,5,Best beginner book. Been looking for somethin...,Looked online for years for something like thi...,1680450263,2020-08-12 11:06:00,0,True
4,4,Referance Guide,Good reference guide for the basics,1889892742,"13 Nov 2014, 18:55",0,True
...,...,...,...,...,...,...,...
1828,5,"love it, love it",The book was all an more than I expected ... l...,1574328522,"07 Mar 2017, 14:04",0,True
1829,5,A good old fashioned ghost story!,I loved this book. It had all the scares and s...,1694621731,2019-12-07 11:54:25,0,False
1830,5,Very insightful and helpful,"I found Mr. Ottinger's perspectives, insights,...",0071496769,2012-01-22 12:26:00,0,True
1831,5,Powerful & Convicting Reminder of God's Truth ...,Rosaria is an excellent writer with a powerful...,1884527388,"13 Apr 2013, 05:35",0,True
1832,3,Not as good as most,I have read many books about special forces te...,0316185361,2012-10-01 04:14:00,2,True

In [30]:
import pandas as pd
from datetime import datetime
import random
# 路径配置
input_path = "../amazonreview_query\origin_dataset/review_query.json"
output_path = "../amazonreview_query\origin_dataset/review_query.json"

# ====== 时间格式化函数 ======
def format_timestamp_randomly(ts_ms):
    try:
        dt = datetime.fromtimestamp(ts_ms / 1000)
        formats = [
            dt.strftime("%Y-%m-%d %H:%M:%S"),           # ISO 风格
            dt.strftime("%B %d, %Y at %I:%M %p"),       # 美式自然语言
            dt.strftime("%d %b %Y, %H:%M")              # 英式简洁风格
        ]
        return random.choice(formats)
    except Exception as e:
        print(f"❌ 时间转换错误: {e}")
        return ts_ms  # 如果时间格式错误，保留原始值

# ====== 读取数据 ======
df = pd.read_json(input_path, lines=True, convert_dates=False)

# ====== 转换 review_time 列 ======
if "review_time" in df.columns:
    df["review_time"] = df["review_time"].apply(
        lambda ts: format_timestamp_randomly(ts) if pd.notnull(ts) else ts
    )
    print("✅ 'review_time' 字段已转换为自然语言格式")
else:
    print("⚠️ 'review_time' 字段不存在，未做处理")

# ====== 保存结果 ======
df.to_json(output_path, orient="records", lines=True)
print(f"✅ 转换后的文件已保存到：{output_path}")

✅ 'review_time' 字段已转换为自然语言格式
✅ 转换后的文件已保存到：../amazonreview_query\origin_dataset/review_query.json

In [23]:
print(df["timestamp"].iloc[0])
print(type(df["timestamp"].iloc[0]))

November 25, 2012 at 02:52 AM
<class 'str'>

In [33]:
print(df_review.dtypes)
print(df_meta.dtypes)

rating                int64
title                object
text                 object
parent_asin          object
review_time          object
helpful_vote          int64
verified_purchase      bool
dtype: object
title             object
subtitle          object
author            object
rating_number      int64
features          object
description       object
price            float64
store             object
categories        object
details           object
parent_asin       object
dtype: object

In [13]:
import json
import random
from tqdm import tqdm
from openai import AzureOpenAI

# ====== Azure OpenAI 配置 ======
client = AzureOpenAI(
    api_key="609ced4d971240b8a08f7fb0e6d846ea",
    api_version="2024-08-01-preview",
    azure_endpoint="https://promptdelta-nc.openai.azure.com",  # 不要加 /v1
)

deployment_name = "gpt-4o-mini"  # 在 Azure Portal 的 Deployments 中查看

# ====== 文件路径 ======
input_path = "../amazonreview_query\origin_dataset/light_meta_edited.json"
output_path = "../amazonreview_query\origin_dataset/books_info.json"



# ========== 细节改写函数 ==========
def enrich_details_with_llm(details_dict):
    """使用 LLM 将 details 字典改写成自然语言描述"""

    if not isinstance(details_dict, dict):
        return ""

    # 只保留非空字段
    filtered = {k: v for k, v in details_dict.items() if v and v != "null"}

    if not filtered:
        return ""

    prompt = (
        f"The following dictionary describes a book's details:\n{json.dumps(filtered, indent=2)}\n\n"
        "Please rewrite this dictionary into a single natural English paragraph. "
        "Include all factual information, do not omit any values, and do not mention the keys explicitly like 'Publisher:'. "
        "Use fluent, professional English."
    )

    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a helpful assistant that rewrites book metadata into natural English sentences."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=150
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        print(f"❌ Error enriching details: {e}")
        return ""

# ========== 主处理流程 ==========
with open(input_path, "r", encoding="utf-8") as fin, \
     open(output_path, "w", encoding="utf-8") as fout:

    for line in tqdm(fin, desc="📚 Processing rows"):
        try:
            entry = json.loads(line)

            details = entry.get("details", {})
            rewritten_details = enrich_details_with_llm(details)
            entry["details"] = rewritten_details

            fout.write(json.dumps(entry, ensure_ascii=False) + "\n")

        except Exception as e:
            print(f"❌ Skipped a line due to error: {e}")
            continue

print(f"\n✅ Finished writing to: {output_path}")

📚 Processing rows: 200it [06:26,  1.93s/it]

✅ Finished writing to: ../amazonreview_query\origin_dataset/books_info.json

In [18]:
import pandas as pd
import random
from datetime import datetime

# ====== 路径配置 ======
input_path = "../amazonreview_query\origin_dataset\light_review_edited.json"
output_path = "../amazonreview_query\origin_dataset/review_query.json"

# ====== 时间格式化函数 ======
def format_timestamp_randomly(ts_string):
    try:
        dt = pd.to_datetime(ts_string)  # 将字符串转换为 datetime 对象
        formats = [
            dt.strftime("%Y-%m-%d %H:%M:%S"),           # ISO 风格
            dt.strftime("%B %d, %Y at %I:%M %p"),       # 美式自然语言
            dt.strftime("%d %b %Y, %H:%M"),             # 英式简洁风格
        ]
        return random.choice(formats)
    except Exception as e:
        print(f"❌ 时间格式错误: {ts_string}, error: {e}")
        return ts_string  # 如果解析失败，保留原始字符串

# ====== 加载数据 ======
df = pd.read_json(input_path, lines=True)


# ====== 转换 timestamp 字段 ======
if "timestamp" in df.columns:
    df["timestamp"] = df["timestamp"].apply(lambda ts: format_timestamp_randomly(ts) if pd.notnull(ts) else ts)
    print("✅ 'timestamp' 字段已转换为自然语言格式")
else:
    print("⚠️ 'timestamp' 字段不存在，未做处理")


# ====== 保存结果 ======
df.to_json(output_path, orient="records", lines=True, force_ascii=False)
print(f"✅ 文件已保存到：{output_path}")

✅ 'timestamp' 字段已转换为自然语言格式
✅ 文件已保存到：../amazonreview_query\origin_dataset/review_query.json

In [2]:
import pandas as pd
df_meta = pd.read_json("dataset/googlelocal/light_meta.json", lines=True)

In [9]:
import json
from tqdm import tqdm
from openai import AzureOpenAI

# ====== Azure OpenAI 配置 ======
client = AzureOpenAI(
    api_key="609ced4d971240b8a08f7fb0e6d846ea",
    api_version="2024-08-01-preview",
    azure_endpoint="https://promptdelta-nc.openai.azure.com",  # 不要加 /v1
)

deployment_name = "gpt-4o-mini"  # 在 Azure Portal 的 Deployments 中查看

# ====== 文件路径 ======
INPUT_PATH = "dataset/googlelocal/light_meta.json"
OUTPUT_PATH = "dataset/googlelocal/light_meta_withdescip.json"

# ====== 生成描述（包含 category + location） ======
def generate_category_description(category_list, address):
    category = category_list[0] if isinstance(category_list, list) and category_list else "local business"

    # 提取地址中的城市 + 州 ZIP（如 "Los Angeles, CA 90023"）
    location = ""
    if isinstance(address, str) and ',' in address:
        parts = address.strip().split(',')
        if len(parts) >= 3:
            city = parts[-2].strip()
            state_zip = parts[-1].strip()
            location = f"{city}, {state_zip}"

    # 构造提示词
    prompt = (
        f"Write a natural and concise one-sentence English description for a business that is a {category} "
        f"located in {location}. "
        f"The sentence must include the phrase '{category}' and mention the location '{location}'. "
        "Do not mention the business name. Use a helpful, informative tone."
    )

    try:
        response = client.chat.completions.create(
            model=deployment_name,
            messages=[
                {"role": "system", "content": "You are a helpful assistant who writes business descriptions."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=60
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"❌ Error generating for category '{category}': {e}")
        return None

# ====== 主循环（可改为前10行为 debug） ======
with open(INPUT_PATH, "r", encoding="utf-8") as fin, \
     open(OUTPUT_PATH, "w", encoding="utf-8") as fout:

    for i, line in enumerate(tqdm(fin)):
        # 只处理前10行可用于 debug
        # if i >= 10:
        #     break

        entry = json.loads(line)
        category_list = entry.get("category", [])
        address = entry.get("address", "")
        old_desc = entry.get("description") or ""

        if category_list:
            new_sentence = generate_category_description(category_list, address)

            if new_sentence:
                if old_desc and not old_desc.endswith('.'):
                    old_desc += "."
                entry["description"] = f"{old_desc.strip()} {new_sentence}"
            else:
                entry["description"] = old_desc  # fallback if generation failed

        fout.write(json.dumps(entry, ensure_ascii=False) + "\n")

print(f"✅ Descriptions updated and saved to: {OUTPUT_PATH}")

79it [01:56,  1.47s/it]

✅ Descriptions updated and saved to: dataset/googlelocal/light_meta_withdescip.json

In [10]:
df_metawithdescrip = pd.read_json("dataset/googlelocal/light_meta_withdescip.json", lines=True)
df_metawithdescrip

,name,address,gmap_id,description,latitude,longitude,category,num_of_reviews,price,hours,MISC,state,relative_results,url
0,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,"This textile exporter located in Los Angeles,...",34.018891,-118.215290,[Textile exporter],6,NaN,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,This vibrant Korean restaurant in Los Angeles...,34.058092,-118.292130,[Korean restaurant],18,NaN,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,"This fabric store in Los Angeles, CA 90021 of...",34.023669,-118.232930,[Fabric store],6,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,"This fabric store in Los Angeles, CA 90021 of...",34.036694,-118.249421,[Fabric store],7,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Matrix International Textiles,"Matrix International Textiles, 1363 S Bonnie B...",0x80c2cf163db6bc89:0x219484e2edbcfa41,"This Fabric store in Commerce, CA 90023 offer...",34.015505,-118.181839,[Fabric store],6,NaN,"[[Thursday, 8:30AM–5:30PM], [Friday, 8:30AM–5:...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5:30PM,"[0x80c2cf042a5d9561:0xd0024ad6f81f1335, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Taitz Orly DDS,"Taitz Orly DDS, 29839 Santa Margarita Pkwy, Ra...",0x80dcebb0f57d2047:0x9e642a2ee5eed29c,"This Dentist in Rancho Santa Margarita, CA 92...",33.638067,-117.611222,[Dentist],48,NaN,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM,"[0x80dcebb0f4c49b8f:0xf38d68e0039fde6a, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...
75,St John Knits International Inc,"St John Knits International Inc, 17522 Armstro...",0x80dcde96809ca927:0x9ba5b9ae5526f1fc,"This Women's clothing store in Irvine, CA 926...",33.690160,-117.849098,[Women's clothing store],8,NaN,"[[Thursday, 10AM–6PM], [Friday, 10AM–6PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 10AM,"[0x80dcdcf56eb54575:0x233b36a32226f099, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...
76,NEX Barbershop,"NEX Barbershop, 3238 Guadalcanal Rd, Coronado,...",0x80d9532636343fc5:0x8ab94fe13542f7b,"This Barber shop in Coronado, CA 92118 offers...",32.676192,-117.160373,[Barber shop],8,NaN,"[[Thursday, 7AM–5PM], [Friday, 7AM–5PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 5PM,"[0x80d9534c8adf3713:0x4ac67169e4a52318, 0x80d9...",https://www.google.com/maps/place//data=!4m2!3...
77,Widows Peak Salon,"Widows Peak Salon, 970 N Broadway Suite 214A, ...",0x80c2c6594138441d:0x59088f7293270c3f,"This modern hair salon in Los Angeles, CA 900...",34.066292,-118.235713,[Hair salon],35,NaN,"[[Thursday, 11AM–8PM], [Friday, 11AM–7PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 11AM,"[0x80c2c65afdaac50b:0x1a6b3ee710d6be7c, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
78,The Dream Junction,"The Dream Junction, 1915 S Susan St, Santa Ana...",0x80dcd8970ce4c31b:0x60ba91dcb32c3f3c,"Located in Santa Ana, CA 92704, this digital ...",33.721438,-117.911658,"[Digital printer, Garment exporter]",48,NaN,"[[Thursday, 9AM–7PM], [Friday, 9AM–7PM], [Satu...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 9AM,"[0x80dcde8dfce91103:0x32cecf2be8ce14b3, 0x80dc...",https://www.google.com/maps/place//data=!4m2!3...

In [ ]:
import json

INPUT_PATH = "dataset/googlelocal/light_meta_withdescip.json"
OUTPUT_PATH = "dataset/googlelocal/light_meta_LLM.json"

fields_to_remove = ["category", "address", "latitude", "longitude"]

with open(INPUT_PATH, "r", encoding="utf-8") as fin, \
     open(OUTPUT_PATH, "w", encoding="utf-8") as fout:

    for line in fin:
        entry = json.loads(line)

        for field in fields_to_remove:
            entry.pop(field, None)  # 安全删除：即使字段不存在也不会报错

        fout.write(json.dumps(entry, ensure_ascii=False) + "\n")

print(f"✅ Removed {fields_to_remove} and saved to: {OUTPUT_PATH}")

✅ Removed ['category', 'address', 'latitude', 'longitude'] and saved to: dataset/googlelocal/light_meta_final.json